//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalker.V3Files.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOG()
        {
            this.WALKS = new HashSet<WALK>();
        }
    
        public int DogID { get; set; }
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public bool Alone { get; set; }
    
        public virtual OWNER OWNER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WALK> WALKS { get; set; }
    }
}
