//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalker.V3Files.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DWEntities : DbContext
    {
        public DWEntities()
            : base("name=DWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOG> DOGS { get; set; }
        public virtual DbSet<OWNER> OWNERS { get; set; }
        public virtual DbSet<WALK> WALKS { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
    }
}
