//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalker.V3Files.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public int OwnerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Postal { get; set; }
        public int WalkID { get; set; }
        public bool Alone { get; set; }
        public string Time { get; set; }
    }
}
